In [6]:
import numpy as np
from scipy import stats
import seaborn as sns

EXERCISE 1. 
Suppose scores on exams in statistics are normally distributed with an unknown population mean and a population standard deviation of 3 points. A random sample of 36 scores is taken and gives a sample mean (sample  mean score) of 68. Find a confidence interval estimate for the population mean exam score (the mean score on all exams).
Find a 90% confidence interval for the true (population) mean of statistics exam scores. 


In [47]:
sigma = 3, 
xbar = 68,
n = 36
z = 1.645 #for  ci = 90%

In [49]:
sem = sigma/np.sqrt(n)
print(sem)

[0.5]


In [50]:
moe = 1.645 * sem 
print(moe)

[0.8225]


In [51]:
#lower  = xbar - z* (σ/√n)

lower  = xbar - moe
print(lower)

[67.1775]


In [52]:
#upper = xbar + z* (σ/√n)
upper  = xbar + moe
print(upper)

[68.8225]


In [53]:
ci = (lower, upper)
print(ci)

(array([67.1775]), array([68.8225]))


In [55]:
#second solution 
stats.norm.interval(0.90, loc=xbar, scale=sem )

(array([67.17757319]), array([68.82242681]))

EXERCISE 2. 
What is the normal body temperature for healthy humans? A random sample of 130 healthy human body temperatures provided by Allen Shoemaker7 yielded 98.25 degrees and standard deviation 0.73 degrees. 
Give a 99% confidence interval for the average body temperature of healthy people.


In [56]:
sigma = 0.73, 
xbar = 98.25,
n = 130
z = 2.576 #for  ci = 99%

In [57]:
sem = sigma/np.sqrt(n)
print(sem)

[0.06402524]


In [58]:
moe = 2.576 * sem 
print(moe)

[0.16492901]


In [59]:
#lower  = xbar - z* (σ/√n)
lower  = xbar - moe
lower

array([98.08507099])

In [60]:
#upper = xbar + z* (σ/√n)
upper  = xbar + moe
upper

array([98.41492901])

In [61]:
ci = (lower, upper)
ci

(array([98.08507099]), array([98.41492901]))

In [62]:
#second solution 
stats.norm.interval(0.99, loc=xbar, scale=sem )

(array([98.08508192]), array([98.41491808]))

EXERCISE 3. 
The administrators for a hospital wished to estimate the average number of days required for inpatient treatment of patients between the ages of 25 and 34. A random sample of 500 hospital patients between these ages produced a mean and standard deviation equal to 5.4 and 3.1 days, respectively.
Construct a 95% confidence interval for the mean length of stay for the population of patients from which the sample was drawn.


In [63]:
sigma = 3.1 
xbar = 5.4
n = 500
z = 1.96 #for  ci = 95%

In [64]:
sem = sigma/np.sqrt(n)
print(sem)

0.13863621460498696


In [65]:
stats.t.interval(0.95, df=n-1, loc=xbar, scale=sem)

(5.127617354510309, 5.672382645489692)