## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [2]:
import numpy as np
from scipy import stats 
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [3]:
samples = np.random.normal(100, 15, 1000)
samples

array([ 79.57675861, 110.35235407, 107.84188207,  97.44732528,
       103.02565983,  96.93167203,  88.40106363, 108.71165136,
        82.93517936,  70.46012639, 123.69823964, 100.06769575,
        74.78585694,  83.49983726,  68.17852006, 108.87844467,
       109.67159704,  77.01183514,  67.2413366 ,  97.8470723 ,
       128.00326469,  89.84446525,  84.57265211, 102.1928684 ,
        91.86526898, 107.49121455,  75.86783676,  98.23998387,
        82.00821937,  85.17024006,  91.59582895, 117.62863654,
       109.0323554 , 118.89592417,  93.06770855,  91.3992808 ,
       106.37000325, 113.57860071,  91.61713743,  85.52613846,
       131.97372612,  99.20929386, 116.78399174, 108.70705689,
       107.38926428, 117.01854479,  95.65160551, 106.37856286,
        96.06893851,  88.74965514,  77.08296388, 101.63013165,
       101.37284612,  97.37482893,  80.21498908,  98.2976706 ,
       103.81331244,  94.56547986,  86.24060713, 103.50214252,
       111.03478244,  72.9906826 ,  82.62549839, 114.17

Compute the **mean**, **median**, and **mode**

In [4]:
mean = np.mean(samples)
median = np.median(samples)
mode = stats.mode(samples)

print(mean)
print(median)
print(mode)

100.34048920719809
99.74417558129059
ModeResult(mode=array([48.07241972]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [5]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr1 = q3 -q1
iqr2 = stats.iqr(samples)

print(min)
print(max)
print(q1)
print(q3)
print(iqr1)
print(iqr2)


48.072419721618054
153.1496091176068
90.85237357233524
110.07788168972024
19.225508117385004
19.225508117385004


Compute the **variance** and **standard deviation**

In [6]:
variance = np.var(samples)
std_dev = np.std(samples)

print(variance)
print(std_dev)

224.06181610057357
14.968694535615775


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [7]:
import scipy
from scipy.stats import kurtosis, skew
from scipy import stats

In [8]:
skewness = scipy.stats.skew(samples)
kurtosis = scipy.stats.kurtosis(samples)

print(kurtosis)
print(skewness)



0.24230463293541415
0.03798986681121944


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [9]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [10]:
y = np.array([0,1,2,34,-24,5,324,7,-3,9])
y

array([  0,   1,   2,  34, -24,   5, 324,   7,  -3,   9])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [11]:
r = np.corrcoef(x, y)
print(r)

[[1.         0.17516223]
 [0.17516223 1.        ]]


## Pandas Correlation Calculation

Run the code below

In [12]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
print(x)
print(y)

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0     2
1     1
2     4
3     5
4     8
5    12
6    18
7    25
8    96
9    48
dtype: int64


Call the relevant method  to calculate Pearson's r correlation.

In [13]:
r = stats.pearsonr(x,y)
print(r)

(0.758640289091187, 0.010964341301680813)


OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [14]:
rho = stats.spearmanr(x,y)
print(rho)

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)


## Seaborn Dataset Tips

Import Seaborn Library

In [15]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [16]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [17]:
tips.describe()


total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [18]:
a = tips.corr()
print(a)

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000


In [19]:
a = np.arange(6).reshape(3, 2)
b = np.arange(6, 15).reshape(3, 3)
print(a)
print(b)

# vertical stacking (row wise)
#np.vstack((a, b))
# horizontal stacking (column wise)
np.hstack((a, b))

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


array([[ 0,  1,  6,  7,  8],
       [ 2,  3,  9, 10, 11],
       [ 4,  5, 12, 13, 14]])